"""api key usage counters

Revision ID: 14cca3158800
Revises: 839cb6a22671
Create Date: 2026-07-14 23:19:04.896336
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14cca3158800'
down_revision: Union[str, None] = '839cb6a22671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage',
    sa.Column('usage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.api_key_id'], ),
    sa.PrimaryKeyConstraint('usage_id'),
    sa.UniqueConstraint('api_key_id', 'date', name='uq_api_key_usage_key_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key_usage')
    # ### end Alembic commands ###
