"""shareable memo links

Revision ID: 7f042efa7933
Revises: bacda051209f
Create Date: 2026-07-14 22:13:48.386712
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f042efa7933'
down_revision: Union[str, None] = 'bacda051209f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_deal_queries_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_queries_share_token'))
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
