"""saved comps watchlist

Revision ID: 839cb6a22671
Revises: 7f042efa7933
Create Date: 2026-07-14 22:35:17.415003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '839cb6a22671'
down_revision: Union[str, None] = '7f042efa7933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_comps',
    sa.Column('saved_comp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('saved_comp_id'),
    sa.UniqueConstraint('owner_id', 'transaction_id', name='uq_saved_comp_owner_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_comps')
    # ### end Alembic commands ###
