"""team seat billing organizations and invites

Revision ID: adf5e5e6b809
Revises: c177bb142f10
Create Date: 2026-07-14 16:08:45.783216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adf5e5e6b809'
down_revision: Union[str, None] = 'c177bb142f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('seat_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        # SQLite's batch-alter mode rebuilds the table under the hood and
        # requires every tracked constraint to have an explicit name (an
        # autogenerated create_foreign_key(None, ...) fails with "Constraint
        # must have a name" on SQLite specifically -- Postgres doesn't need
        # this, but naming it keeps both dialects identical).
        batch_op.create_foreign_key(
            'fk_users_organization_id_organizations', 'organizations', ['organization_id'], ['organization_id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_organization_id_organizations', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_token_hash'))

    op.drop_table('team_invites')
    op.drop_table('organizations')
    # ### end Alembic commands ###
