"""saved searches for alert digests

Revision ID: bd907cbfd885
Revises: 14cca3158800
Create Date: 2026-07-14 23:26:42.459939
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd907cbfd885'
down_revision: Union[str, None] = '14cca3158800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('saved_search_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('community', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('saved_search_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
