"""stripe webhook idempotency table

Revision ID: c177bb142f10
Revises: 0222f6da16b8
Create Date: 2026-07-14 16:01:17.793118
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c177bb142f10'
down_revision: Union[str, None] = '0222f6da16b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_webhook_events')
    # ### end Alembic commands ###
