"""session metadata on auth_tokens

Revision ID: d6ef68d02c77
Revises: adf5e5e6b809
Create Date: 2026-07-14

Phase 16: the active-sessions UI (list devices, revoke one, log out
everywhere) needs something to actually show the user besides an opaque
token id -- these three nullable columns are only populated for
token_type='refresh' rows going forward; existing rows just read as NULL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6ef68d02c77'
down_revision: Union[str, None] = 'adf5e5e6b809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
